# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

env:
  SOLUTION_APP: src/Giana.Src.sln
  SOLUTION_TESTS: tests/Giana.Tests.sln
  SOLUTION_EXAMPLES: examples/Giana.Examples.sln

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.SOLUTION_APP}}
    - name: Build
      run: dotnet build --no-restore ${{env.SOLUTION_APP}}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{env.SOLUTION_APP}}
    - name: Restore tests dependencies
      run: dotnet restore ${{env.SOLUTION_TESTS}}    
    - name: Build tests
      run: dotnet build --no-restore ${{env.SOLUTION_TESTS}}
    - name: Restore examples dependencies
      run: dotnet restore ${{env.SOLUTION_EXAMPLES}}          
    - name: Build examples
      run: dotnet build --no-restore ${{env.SOLUTION_EXAMPLES}}