name: Pack Preview

on:
  push:
    tags:
      - "*"
    branches: [ "preview/[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    tags:
      - "*"
    branches: [ "preview/[0-9]+.[0-9]+.[0-9]+" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF_NAME/preview\/}-preview${{github.run_number}}" >> $GITHUB_ENV
    - name: Show VERSION
      run: echo "${VERSION}"
    - name: Pack API
      run: dotnet pack --configuration Release src/api/Giana.Api.csproj -p:Version=${VERSION} --output .
    - name: Pack APP
      run: dotnet pack --configuration Release src/app/Giana.App.csproj -p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push Giana.Api.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${GITHUB_TOKEN}
      env:
       GITHUB_TOKEN: ${{ secrets.PUSH_NUGET }}
