# https://acraven.medium.com/a-nuget-package-workflow-using-github-actions-7da8c6557863

name: Pack Preview

on:
  push:
    branches: [ "main", "workflows" ]
    tags:
      - '*'
  pull_request:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"
    branches: [ "main", "workflows" ]

env:
  SOLUTION_FILE_PATH: src/Giana.Src.sln

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
    - name: Show VERSION
      run: echo "${VERSION}"
    - name: Pack API
      run: dotnet pack --configuration Release src/api/Giana.Api.csproj -p:Version=${VERSION} --output .
    - name: Pack APP
      run: dotnet pack --configuration Release src/app/Giana.App.csproj -p:Version=${VERSION} --output .
#    - name: Push
#      run: dotnet nuget push NuGet.Workflow.${VERSION}.nupkg --source https://nuget.pkg.github.com/mrstefangrimm/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
